export const INITIAL_USERS = [
  { id: 'usr_admin', username: 'admin', password: 'admin123', name: 'System Admin', role: 'admin', avatar: '👑', code: 'ADMIN' },
  { id: 'usr_1', username: 'ahmed', password: '123456', name: 'Ahmed Ali', role: 'qa_auditor', avatar: '👨‍💼', code: 'QA-101' },
  { id: 'usr_2', username: 'sara', password: '123456', name: 'Sara Mahmoud', role: 'qa_auditor', avatar: '👩‍💼', code: 'QA-102' },
  { id: 'usr_3', username: 'khaled', password: '123456', name: 'Khaled Al-Otaibi', role: 'qa_auditor', avatar: '👨‍💻', code: 'QA-103' },
  { id: 'usr_4', username: 'maryam', password: '123456', name: 'Maryam Ibrahim', role: 'qa_auditor', avatar: '👩‍💻', code: 'QA-104' },
];

export const INITIAL_BATCHES = [
  {
    id: 'batch_101',
    name: 'Main Batch 1 (September Calls A)',
    fileName: 'calls_september_batch1.xlsx',
    uploadedAt: '2026-09-20 09:00:00',
    uploadedBy: 'admin',
    isVisible: true,
  },
  {
    id: 'batch_102',
    name: 'Batch 2 (Complex Tech Support Calls B)',
    fileName: 'calls_september_batch2.xlsx',
    uploadedAt: '2026-09-22 10:30:00',
    uploadedBy: 'admin',
    isVisible: true,
  },
];

export const INITIAL_CALLS = [
  {
    id: 'CALL-1001',
    batchId: 'batch_101',
    call_number: '1001',
    agent_name: 'Mohamed Abdullah',
    group_name: 'Tech Support Team A',
    duration_minutes: '02:15',
    ai_overall_score: 85,
    flag_reason: 'None',
    diagnosis_class: 'Billing Inquiry',
    diagnosis_score: 90,
    diagnosis_errors: 'None',
    case_score: 85,
    case_errors: 'Delay in bank field documentation',
    case_reason: 'Agent oversight',
    inquiry_class: 'Monthly Subscription Fee',
    inquiry_score: 95,
    inquiry_errors: 'None',
    inquiry_reason: 'Routine inquiry',
    problem_class: 'Activation Issue Resolution',
    problem_score: 80,
    problem_errors: 'Activation duration not clarified',
    problem_reason: 'Non-compliance with script',
    answer_ending_score: 100,
    answer_ending_missing: 'None',
    answer_ending_reason: 'Excellent closing',
    comm_score: 90,
    comm_issue: 'Slightly low tone',
    comm_reason: 'Agent calmness',
    violation_highest_severity: 'Low',
    violation_reasons: 'None',
    call_date: '2026-09-20 10:15:00',
    snapshot_at: '2026-09-20 10:20:00',
    
    status: 'unlocked',
    lockedBy: null,
    matching: null,
    policy: null,
    description: '',
    qa_answer: null,
    qa_skills: null,
    qa_diagnosis: null,
    qa_solve: null,
    qa_inquiries: null,
    qa_case: null,
    final_score: null,
    evaluatedBy: null,
    evaluatedAt: null,
  },
  {
    id: 'CALL-1002',
    batchId: 'batch_101',
    call_number: '1002',
    agent_name: 'Fatima Al-Zahra',
    group_name: 'Sales Team B',
    duration_minutes: '05:40',
    ai_overall_score: 62,
    flag_reason: 'Exceeded handling time limit',
    diagnosis_class: 'Package Upgrade Request',
    diagnosis_score: 70,
    diagnosis_errors: 'Customer identity not verified',
    case_score: 60,
    case_errors: 'Failed to open new ticket',
    case_reason: 'Procedure ignored',
    inquiry_class: 'Annual Discount Offers',
    inquiry_score: 75,
    inquiry_errors: 'Outdated information provided',
    inquiry_reason: 'Relied on old guide',
    problem_class: 'Payment Processing',
    problem_score: 55,
    problem_errors: 'Error entering discount value',
    problem_reason: 'Agent rushed',
    answer_ending_score: 70,
    answer_ending_missing: 'No upsell services offered',
    answer_ending_reason: 'Abrupt closing',
    comm_score: 60,
    comm_issue: 'Interrupted customer twice',
    comm_reason: 'Poor active listening',
    violation_highest_severity: 'Medium',
    violation_reasons: 'Security protocol breach',
    call_date: '2026-09-21 11:30:00',
    snapshot_at: '2026-09-21 11:40:00',
    
    status: 'completed',
    lockedBy: null,
    matching: 'Mismatch',
    policy: 'Both AI & Quality Policies Exist',
    description: 'Noticed error in entering upgrade data and security verification steps were skipped.',
    qa_answer: 75,
    qa_skills: 60,
    qa_diagnosis: 65,
    qa_solve: 50,
    qa_inquiries: 70,
    qa_case: 55,
    final_score: 62.5,
    evaluatedBy: { userId: 'usr_1', userName: 'Ahmed Ali' },
    evaluatedAt: '2026-09-21 14:20:00',
  },
  {
    id: 'CALL-1003',
    batchId: 'batch_101',
    call_number: '1003',
    agent_name: 'Omar Al-Farooq',
    group_name: 'Tech Support Team A',
    duration_minutes: '08:45',
    ai_overall_score: 92,
    flag_reason: 'None',
    diagnosis_class: 'Sudden Service Outage',
    diagnosis_score: 95,
    diagnosis_errors: 'None',
    case_score: 90,
    case_errors: 'None',
    case_reason: 'Accurately documented',
    inquiry_class: 'Router Reset Steps',
    inquiry_score: 95,
    inquiry_errors: 'None',
    inquiry_reason: 'Clear explanation',
    problem_class: 'Signal Resend',
    problem_score: 90,
    problem_errors: 'None',
    problem_reason: 'Root cause resolved',
    answer_ending_score: 95,
    answer_ending_missing: 'None',
    answer_ending_reason: 'Warm customer farewell',
    comm_score: 95,
    comm_issue: 'None',
    comm_reason: 'Professional & polite',
    violation_highest_severity: 'None',
    violation_reasons: 'None',
    call_date: '2026-09-21 14:10:00',
    snapshot_at: '2026-09-21 14:25:00',
    
    status: 'locked',
    lockedBy: { userId: 'usr_2', userName: 'Sara Mahmoud', lockedAt: '2026-09-22 13:00:00' },
    matching: null,
    policy: null,
    description: '',
    qa_answer: null,
    qa_skills: null,
    qa_diagnosis: null,
    qa_solve: null,
    qa_inquiries: null,
    qa_case: null,
    final_score: null,
    evaluatedBy: null,
    evaluatedAt: null,
  },
  {
    id: 'CALL-1004',
    batchId: 'batch_102',
    call_number: '1004',
    agent_name: 'Reem Al-Shammari',
    group_name: 'Customer Complaints Team C',
    duration_minutes: '12:10',
    ai_overall_score: 78,
    flag_reason: 'Long duration call',
    diagnosis_class: 'Invoice Amount Dispute',
    diagnosis_score: 80,
    diagnosis_errors: 'Delay clarifying discount details',
    case_score: 75,
    case_errors: 'Complaint misclassified',
    case_reason: 'Categorization error',
    inquiry_class: 'Monthly Usage Breakdown',
    inquiry_score: 85,
    inquiry_errors: 'None',
    inquiry_reason: 'Points explained clearly',
    problem_class: 'Temporary Financial Settlement',
    problem_score: 75,
    problem_errors: 'Terms & conditions not detailed',
    problem_reason: 'Call time constraint',
    answer_ending_score: 80,
    answer_ending_missing: 'Satisfaction check omitted',
    answer_ending_reason: 'Rushed closing',
    comm_score: 80,
    comm_issue: 'Slight initial hesitation',
    comm_reason: 'Temporary confusion',
    violation_highest_severity: 'Low',
    violation_reasons: 'Response delay',
    call_date: '2026-09-22 09:15:00',
    snapshot_at: '2026-09-22 09:30:00',
    
    status: 'unlocked',
    lockedBy: null,
    matching: null,
    policy: null,
    description: '',
    qa_answer: null,
    qa_skills: null,
    qa_diagnosis: null,
    qa_solve: null,
    qa_inquiries: null,
    qa_case: null,
    final_score: null,
    evaluatedBy: null,
    evaluatedAt: null,
  },
  {
    id: 'CALL-1005',
    batchId: 'batch_102',
    call_number: '1005',
    agent_name: 'Youssef Mansour',
    group_name: 'Tech Support Team A',
    duration_minutes: '16:50',
    ai_overall_score: 50,
    flag_reason: 'Customer escalation & poor handling',
    diagnosis_class: 'Home Maintenance Issue',
    diagnosis_score: 45,
    diagnosis_errors: 'Technical issue misunderstood',
    case_score: 50,
    case_errors: 'Ticket closed unresolved',
    case_reason: 'Direct guide violation',
    inquiry_class: 'Technician Visit Slot',
    inquiry_score: 60,
    inquiry_errors: 'Wrong date provided',
    inquiry_reason: 'Schedule not checked',
    problem_class: 'Maintenance Schedule Booking',
    problem_score: 40,
    problem_errors: 'Maintenance request failed',
    problem_reason: 'System error unhandled',
    answer_ending_score: 50,
    answer_ending_missing: 'Disconnected while customer upset',
    answer_ending_reason: 'Agent withdrawal',
    comm_score: 45,
    comm_issue: 'Clear frustration & stress',
    comm_reason: 'Weak de-escalation skills',
    violation_highest_severity: 'High',
    violation_reasons: 'Unresolved ticket closure',
    call_date: '2026-09-22 11:00:00',
    snapshot_at: '2026-09-22 11:20:00',
    
    status: 'completed',
    lockedBy: null,
    matching: 'Match',
    policy: 'Both AI & Quality Policies Exist',
    description: 'AI evaluation accurate. Agent committed severe violations; report submitted to TL.',
    qa_answer: 50,
    qa_skills: 45,
    qa_diagnosis: 45,
    qa_solve: 40,
    qa_inquiries: 50,
    qa_case: 40,
    final_score: 45.0,
    evaluatedBy: { userId: 'usr_3', userName: 'Khaled Al-Otaibi' },
    evaluatedAt: '2026-09-22 12:15:00',
  }
];
